// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $AnalyticsIsland from "./islands/AnalyticsIsland.tsx";
import * as $BreedSelect from "./islands/BreedSelect.tsx";
import * as $CarouselControls from "./islands/CarouselControls.tsx";
import * as $CartDrawer from "./islands/CartDrawer.tsx";
import * as $DiscountTag from "./islands/DiscountTag.tsx";
import * as $Faq from "./islands/Faq.tsx";
import * as $HeaderSearchContainer from "./islands/HeaderSearchContainer.tsx";
import * as $Search from "./islands/Search.tsx";
import * as $SearchInputIsland from "./islands/SearchInputIsland.tsx";
import * as $StickerArea from "./islands/StickerArea.tsx";
import * as $athena_SizesContent from "./islands/athena/SizesContent.tsx";
import * as $bag_RemoveProduct from "./islands/bag/RemoveProduct.tsx";
import * as $bundle_AddBundleToCart from "./islands/bundle/AddBundleToCart.tsx";
import * as $bundle_ProductBundleCardSkus from "./islands/bundle/ProductBundleCardSkus.tsx";
import * as $bundle_ProductBundlePrices from "./islands/bundle/ProductBundlePrices.tsx";
import * as $bundle_ProductBundleSelectionControls from "./islands/bundle/ProductBundleSelectionControls.tsx";
import * as $bundle_ProductBundleThumbs from "./islands/bundle/ProductBundleThumbs.tsx";
import * as $emailCapture_FarmEmailCapture from "./islands/emailCapture/FarmEmailCapture.tsx";
import * as $faq_FAQListItensMenu from "./islands/faq/FAQListItensMenu.tsx";
import * as $faq_FaqForm from "./islands/faq/FaqForm.tsx";
import * as $footer_TalkToUsList from "./islands/footer/TalkToUsList.tsx";
import * as $header_AccountLoggedOut from "./islands/header/AccountLoggedOut.tsx";
import * as $header_SearchRecommendation from "./islands/header/SearchRecommendation.tsx";
import * as $header_ShippingBar from "./islands/header/ShippingBar.tsx";
import * as $header_ShoppingBar from "./islands/header/ShoppingBar.tsx";
import * as $header_menu_MenuDrawer from "./islands/header/menu/MenuDrawer.tsx";
import * as $header_promobar_ClosePromoBarButton from "./islands/header/promobar/ClosePromoBarButton.tsx";
import * as $language_LanguageSelectorButton from "./islands/language/LanguageSelectorButton.tsx";
import * as $modalUser_ContentModalUser from "./islands/modalUser/ContentModalUser.tsx";
import * as $modalUser_login_ConfirmationLink from "./islands/modalUser/login/ConfirmationLink.tsx";
import * as $modalUser_login_FormLogin from "./islands/modalUser/login/FormLogin.tsx";
import * as $modalUser_login_FormLoginNewPassword from "./islands/modalUser/login/FormLoginNewPassword.tsx";
import * as $modalUser_login_FormNewPassword from "./islands/modalUser/login/FormNewPassword.tsx";
import * as $modalUser_login_Login from "./islands/modalUser/login/Login.tsx";
import * as $modalUser_register_FormRegister from "./islands/modalUser/register/FormRegister.tsx";
import * as $modalUser_register_RegisterModal from "./islands/modalUser/register/RegisterModal.tsx";
import * as $modal_HandleCloseModal from "./islands/modal/HandleCloseModal.tsx";
import * as $modal_HandleSubmitModal from "./islands/modal/HandleSubmitModal.tsx";
import * as $modal_handleOpenModal from "./islands/modal/handleOpenModal.ts";
import * as $popup_HandleClosePopup from "./islands/popup/HandleClosePopup.tsx";
import * as $product_Cards_MinicartProductCard from "./islands/product/Cards/MinicartProductCard.tsx";
import * as $product_Cards_MinicartProductCardList from "./islands/product/Cards/MinicartProductCardList.tsx";
import * as $product_ModalTableSizes from "./islands/product/ModalTableSizes.tsx";
import * as $product_ProductCardPrice from "./islands/product/ProductCardPrice.tsx";
import * as $product_ProductCardQuickBuy from "./islands/product/ProductCardQuickBuy.tsx";
import * as $product_SizeTableButton from "./islands/product/SizeTableButton.tsx";
import * as $product_pdp_HandleClickedImageScroll from "./islands/product/pdp/HandleClickedImageScroll.tsx";
import * as $product_pdp_HandleImageSwap from "./islands/product/pdp/HandleImageSwap.tsx";
import * as $product_pdp_HandleImageSwapModal from "./islands/product/pdp/HandleImageSwapModal.tsx";
import * as $product_pdp_HandleModalProductMedias from "./islands/product/pdp/HandleModalProductMedias.tsx";
import * as $product_pdp_HandleProductImage from "./islands/product/pdp/HandleProductImage.tsx";
import * as $product_pdp_ProductAddToCart from "./islands/product/pdp/ProductAddToCart.tsx";
import * as $product_pdp_ProductCopyLink from "./islands/product/pdp/ProductCopyLink.tsx";
import * as $product_pdp_ProductPrice from "./islands/product/pdp/ProductPrice.tsx";
import * as $product_pdp_ProductQuantity from "./islands/product/pdp/ProductQuantity.tsx";
import * as $product_pdp_ProductSimilarsControls from "./islands/product/pdp/ProductSimilarsControls.tsx";
import * as $product_pdp_ProductSkus from "./islands/product/pdp/ProductSkus.tsx";
import * as $product_pdp_ProductSoldout from "./islands/product/pdp/ProductSoldout.tsx";
import * as $promobar_FarmPromoBar from "./islands/promobar/FarmPromoBar.tsx";
import * as $shelf_ApplyFilterButton from "./islands/shelf/ApplyFilterButton.tsx";
import * as $shelf_FilterHandler from "./islands/shelf/FilterHandler.tsx";
import * as $shelf_UpdateURL from "./islands/shelf/UpdateURL.tsx";
import * as $userAccount_ModalExitAccount from "./islands/userAccount/ModalExitAccount.tsx";
import * as $zee_ZeeGlobal from "./islands/zee/ZeeGlobal.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/AnalyticsIsland.tsx": $AnalyticsIsland,
    "./islands/BreedSelect.tsx": $BreedSelect,
    "./islands/CarouselControls.tsx": $CarouselControls,
    "./islands/CartDrawer.tsx": $CartDrawer,
    "./islands/DiscountTag.tsx": $DiscountTag,
    "./islands/Faq.tsx": $Faq,
    "./islands/HeaderSearchContainer.tsx": $HeaderSearchContainer,
    "./islands/Search.tsx": $Search,
    "./islands/SearchInputIsland.tsx": $SearchInputIsland,
    "./islands/StickerArea.tsx": $StickerArea,
    "./islands/athena/SizesContent.tsx": $athena_SizesContent,
    "./islands/bag/RemoveProduct.tsx": $bag_RemoveProduct,
    "./islands/bundle/AddBundleToCart.tsx": $bundle_AddBundleToCart,
    "./islands/bundle/ProductBundleCardSkus.tsx": $bundle_ProductBundleCardSkus,
    "./islands/bundle/ProductBundlePrices.tsx": $bundle_ProductBundlePrices,
    "./islands/bundle/ProductBundleSelectionControls.tsx":
      $bundle_ProductBundleSelectionControls,
    "./islands/bundle/ProductBundleThumbs.tsx": $bundle_ProductBundleThumbs,
    "./islands/emailCapture/FarmEmailCapture.tsx":
      $emailCapture_FarmEmailCapture,
    "./islands/faq/FAQListItensMenu.tsx": $faq_FAQListItensMenu,
    "./islands/faq/FaqForm.tsx": $faq_FaqForm,
    "./islands/footer/TalkToUsList.tsx": $footer_TalkToUsList,
    "./islands/header/AccountLoggedOut.tsx": $header_AccountLoggedOut,
    "./islands/header/SearchRecommendation.tsx": $header_SearchRecommendation,
    "./islands/header/ShippingBar.tsx": $header_ShippingBar,
    "./islands/header/ShoppingBar.tsx": $header_ShoppingBar,
    "./islands/header/menu/MenuDrawer.tsx": $header_menu_MenuDrawer,
    "./islands/header/promobar/ClosePromoBarButton.tsx":
      $header_promobar_ClosePromoBarButton,
    "./islands/language/LanguageSelectorButton.tsx":
      $language_LanguageSelectorButton,
    "./islands/modalUser/ContentModalUser.tsx": $modalUser_ContentModalUser,
    "./islands/modalUser/login/ConfirmationLink.tsx":
      $modalUser_login_ConfirmationLink,
    "./islands/modalUser/login/FormLogin.tsx": $modalUser_login_FormLogin,
    "./islands/modalUser/login/FormLoginNewPassword.tsx":
      $modalUser_login_FormLoginNewPassword,
    "./islands/modalUser/login/FormNewPassword.tsx":
      $modalUser_login_FormNewPassword,
    "./islands/modalUser/login/Login.tsx": $modalUser_login_Login,
    "./islands/modalUser/register/FormRegister.tsx":
      $modalUser_register_FormRegister,
    "./islands/modalUser/register/RegisterModal.tsx":
      $modalUser_register_RegisterModal,
    "./islands/modal/HandleCloseModal.tsx": $modal_HandleCloseModal,
    "./islands/modal/HandleSubmitModal.tsx": $modal_HandleSubmitModal,
    "./islands/modal/handleOpenModal.ts": $modal_handleOpenModal,
    "./islands/popup/HandleClosePopup.tsx": $popup_HandleClosePopup,
    "./islands/product/Cards/MinicartProductCard.tsx":
      $product_Cards_MinicartProductCard,
    "./islands/product/Cards/MinicartProductCardList.tsx":
      $product_Cards_MinicartProductCardList,
    "./islands/product/ModalTableSizes.tsx": $product_ModalTableSizes,
    "./islands/product/ProductCardPrice.tsx": $product_ProductCardPrice,
    "./islands/product/ProductCardQuickBuy.tsx": $product_ProductCardQuickBuy,
    "./islands/product/SizeTableButton.tsx": $product_SizeTableButton,
    "./islands/product/pdp/HandleClickedImageScroll.tsx":
      $product_pdp_HandleClickedImageScroll,
    "./islands/product/pdp/HandleImageSwap.tsx": $product_pdp_HandleImageSwap,
    "./islands/product/pdp/HandleImageSwapModal.tsx":
      $product_pdp_HandleImageSwapModal,
    "./islands/product/pdp/HandleModalProductMedias.tsx":
      $product_pdp_HandleModalProductMedias,
    "./islands/product/pdp/HandleProductImage.tsx":
      $product_pdp_HandleProductImage,
    "./islands/product/pdp/ProductAddToCart.tsx": $product_pdp_ProductAddToCart,
    "./islands/product/pdp/ProductCopyLink.tsx": $product_pdp_ProductCopyLink,
    "./islands/product/pdp/ProductPrice.tsx": $product_pdp_ProductPrice,
    "./islands/product/pdp/ProductQuantity.tsx": $product_pdp_ProductQuantity,
    "./islands/product/pdp/ProductSimilarsControls.tsx":
      $product_pdp_ProductSimilarsControls,
    "./islands/product/pdp/ProductSkus.tsx": $product_pdp_ProductSkus,
    "./islands/product/pdp/ProductSoldout.tsx": $product_pdp_ProductSoldout,
    "./islands/promobar/FarmPromoBar.tsx": $promobar_FarmPromoBar,
    "./islands/shelf/ApplyFilterButton.tsx": $shelf_ApplyFilterButton,
    "./islands/shelf/FilterHandler.tsx": $shelf_FilterHandler,
    "./islands/shelf/UpdateURL.tsx": $shelf_UpdateURL,
    "./islands/userAccount/ModalExitAccount.tsx": $userAccount_ModalExitAccount,
    "./islands/zee/ZeeGlobal.tsx": $zee_ZeeGlobal,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
