// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/deco/analytics.ts";
import * as $$$$$$$$$$$1 from "./apps/deco/crux.ts";
import * as $$$$$$$$$$$2 from "./apps/deco/records.ts";
import * as $$$$$$$$$$$3 from "./apps/deco/shopify.ts";
import * as $$$$$$$$$$$4 from "./apps/site.ts";
import * as $$$$$$$$$$$5 from "./apps/zee.ts";
import * as $$$0 from "./loaders/distributors.ts";
import * as $$$1 from "./loaders/faq.ts";
import * as $$$2 from "./loaders/productType.ts";
import * as $$$3 from "./loaders/shopify/collection/getUrlById.ts";
import * as $$$4 from "./loaders/shopify/product/getProductBundle.ts";
import * as $$$5 from "./loaders/shopify/product/getSimilarsProducts.ts";
import * as $$$6 from "./loaders/shopify/product/getUrlById.ts";
import * as $$$7 from "./loaders/user.ts";
import * as $$$$$$$0 from "./matchers/languagePathnameValue.ts";
import * as $$$$$$0 from "./sections/ErrorPage.tsx";
import * as $$$$$$1 from "./sections/FAQ.tsx";
import * as $$$$$$2 from "./sections/Footer.tsx";
import * as $$$$$$3 from "./sections/Header.tsx";
import * as $$$$$$4 from "./sections/Home/BannerAndCarousel.tsx";
import * as $$$$$$5 from "./sections/Home/BannerAndCarouselGrid.tsx";
import * as $$$$$$6 from "./sections/Home/BannerSkeleton.tsx";
import * as $$$$$$7 from "./sections/Home/CategoryBannerCarousel.tsx";
import * as $$$$$$8 from "./sections/Home/DoubleBanner.tsx";
import * as $$$$$$9 from "./sections/Home/FarmStickerBanner.tsx";
import * as $$$$$$10 from "./sections/Home/FarmStickerEmailCapture.tsx";
import * as $$$$$$11 from "./sections/Home/Marquee.tsx";
import * as $$$$$$12 from "./sections/Home/MiniCardsCarousel.tsx";
import * as $$$$$$13 from "./sections/Home/SingleBanner.tsx";
import * as $$$$$$14 from "./sections/Home/SlimBannerCards.tsx";
import * as $$$$$$15 from "./sections/Institutional/AboutUs.tsx";
import * as $$$$$$16 from "./sections/Institutional/PrivacyPolicy.tsx";
import * as $$$$$$17 from "./sections/Institutional/RefundPolicy.tsx";
import * as $$$$$$18 from "./sections/Institutional/SalesContact.tsx";
import * as $$$$$$19 from "./sections/Institutional/ShippingPolicy.tsx";
import * as $$$$$$20 from "./sections/Institutional/TermsOfService.tsx";
import * as $$$$$$21 from "./sections/Modal.tsx";
import * as $$$$$$22 from "./sections/MultiPages.tsx";
import * as $$$$$$23 from "./sections/Popup.tsx";
import * as $$$$$$26 from "./sections/Product/ProductDetailsPage.tsx";
import * as $$$$$$24 from "./sections/ProductCarousel.tsx";
import * as $$$$$$25 from "./sections/ProductShelf.tsx";
import * as $$$$$$27 from "./sections/SearchResult.tsx";
import * as $$$$$$28 from "./sections/Site/seo/SeoPDPV3.tsx";
import * as $$$$$$29 from "./sections/Site/seo/SeoPLPV3.tsx";
import * as $$$$$$30 from "./sections/Site/seo/SeoV3.tsx";

const manifest = {
  "loaders": {
    "site/loaders/distributors.ts": $$$0,
    "site/loaders/faq.ts": $$$1,
    "site/loaders/productType.ts": $$$2,
    "site/loaders/shopify/collection/getUrlById.ts": $$$3,
    "site/loaders/shopify/product/getProductBundle.ts": $$$4,
    "site/loaders/shopify/product/getSimilarsProducts.ts": $$$5,
    "site/loaders/shopify/product/getUrlById.ts": $$$6,
    "site/loaders/user.ts": $$$7,
  },
  "sections": {
    "site/sections/ErrorPage.tsx": $$$$$$0,
    "site/sections/FAQ.tsx": $$$$$$1,
    "site/sections/Footer.tsx": $$$$$$2,
    "site/sections/Header.tsx": $$$$$$3,
    "site/sections/Home/BannerAndCarousel.tsx": $$$$$$4,
    "site/sections/Home/BannerAndCarouselGrid.tsx": $$$$$$5,
    "site/sections/Home/BannerSkeleton.tsx": $$$$$$6,
    "site/sections/Home/CategoryBannerCarousel.tsx": $$$$$$7,
    "site/sections/Home/DoubleBanner.tsx": $$$$$$8,
    "site/sections/Home/FarmStickerBanner.tsx": $$$$$$9,
    "site/sections/Home/FarmStickerEmailCapture.tsx": $$$$$$10,
    "site/sections/Home/Marquee.tsx": $$$$$$11,
    "site/sections/Home/MiniCardsCarousel.tsx": $$$$$$12,
    "site/sections/Home/SingleBanner.tsx": $$$$$$13,
    "site/sections/Home/SlimBannerCards.tsx": $$$$$$14,
    "site/sections/Institutional/AboutUs.tsx": $$$$$$15,
    "site/sections/Institutional/PrivacyPolicy.tsx": $$$$$$16,
    "site/sections/Institutional/RefundPolicy.tsx": $$$$$$17,
    "site/sections/Institutional/SalesContact.tsx": $$$$$$18,
    "site/sections/Institutional/ShippingPolicy.tsx": $$$$$$19,
    "site/sections/Institutional/TermsOfService.tsx": $$$$$$20,
    "site/sections/Modal.tsx": $$$$$$21,
    "site/sections/MultiPages.tsx": $$$$$$22,
    "site/sections/Popup.tsx": $$$$$$23,
    "site/sections/Product/ProductDetailsPage.tsx": $$$$$$26,
    "site/sections/ProductCarousel.tsx": $$$$$$24,
    "site/sections/ProductShelf.tsx": $$$$$$25,
    "site/sections/SearchResult.tsx": $$$$$$27,
    "site/sections/Site/seo/SeoPDPV3.tsx": $$$$$$28,
    "site/sections/Site/seo/SeoPLPV3.tsx": $$$$$$29,
    "site/sections/Site/seo/SeoV3.tsx": $$$$$$30,
  },
  "matchers": {
    "site/matchers/languagePathnameValue.ts": $$$$$$$0,
  },
  "apps": {
    "site/apps/deco/analytics.ts": $$$$$$$$$$$0,
    "site/apps/deco/crux.ts": $$$$$$$$$$$1,
    "site/apps/deco/records.ts": $$$$$$$$$$$2,
    "site/apps/deco/shopify.ts": $$$$$$$$$$$3,
    "site/apps/site.ts": $$$$$$$$$$$4,
    "site/apps/zee.ts": $$$$$$$$$$$5,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
