// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/storefront/account/signIn.ts";
import * as $$$$$$$$$1 from "./actions/storefront/account/signOut.ts";
import * as $$$$$$$$$2 from "./actions/storefront/account/signUp.ts";

const manifest = {
  "actions": {
    "zee/actions/storefront/account/signIn.ts": $$$$$$$$$0,
    "zee/actions/storefront/account/signOut.ts": $$$$$$$$$1,
    "zee/actions/storefront/account/signUp.ts": $$$$$$$$$2,
  },
  "name": "zee",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
